id: IBB8A616E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T11:24:10+00:00'
last_modified: '2022-06-08T02:05:51.654761+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27309
  title: ས་སྐྱའི་གདུང་རབས་ངོ་མཚར་བང་མཛོད་ཀྱི་ཁ་སྐོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AE70:
      image_group_id: I4280
      title: ''
      total_pages: 810
      order: 1
      base_file: AE70.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
