id: P004582
initial_creation_type: ocr
source_metadata:
  id: bdr:W27309
  title: ས་སྐྱའི་གདུང་རབས་ངོ་མཚར་བང་མཛོད་ཀྱི་ཁ་སྐོང
  author: ''
  volumes:
    679d4ac31a3a4415806711e087094b04:
      image_group_id: I4280
      title: ''
      volume_number: 1
      total_pages: 810
